theme = "m10c"
title = "Youshitsune"

[params]
    author="youshitsune"
    avatar="https://avatars.githubusercontent.com/u/79904009?v=4"
    description = "My name is Luka. I’m 15 years old, I’m learning a lot of things. I’m interested in all natural sciences."
    [[params.social]]
        icon="github"
        name="Github"
        url="https://github.com/youshitsune"
    [[params.social]]
        icon="twitter"
        name="Twitter"
        url="https://twitter.com/youshitsune"
    [[params.social]]
        icon="link"
        name="Links"
        url="https://youshitsune.me/links"

[menu]
    [[menu.main]]
        idenitfier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        idenitfier = "posts"
        name = "Posts"
        url = "posts/"
        weight = 2
