baseURL = "https://youshitsune.me"
languageCode = "en"
defaultContentLanguage = "en"
title = "Youshitsune"
theme = "KeepIt"

paginate = 12
enableEmoji = true
disqusShortname = "youshitsune"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name="Projects"
    url="https://github.com/youshitsune"
  [[menu.main]]
    name="Links"
    url="https://youshitsune.me/links"

[params]
    subtitle = "Youshitsune (Luka Jovanovic)"       # Subtitle
    avatar = "/images/avatar.jpg" #comment it to use gravatar
    socialShare = true

    description = " GCS/CM/ED/M/P/S d s+:- a---- C@>$ UL+++ P L+++ !E- W? !N !o !K-- !w--- !O M-- !V PS !PE Y++ PGP+ !t !5 !X !R tv b+++ DI-- !D G++ e- h !r y? " # site description
    keywords = "" # site keywords


[params.social]
    GitHub = "youshitsune"
    Twitter = "youshisune"
    Email   = "luka@youshitsune.me"

[params.share]
    Twitter = true
    Facebook = true
    Linkedin = true

